### PR TITLE
[Merged by Bors] - Use the rust-cache action

### PR DESCRIPTION
**Pull request by acrrd**

### CODE REVIEW

**Comment by Robert-Steiner** [comment]
I'm fine using it. The only downside I see is that each rust job now caching an additional 120MB as each of them independently fetches and caches the cargo registry. But maybe their clean up at the end compensate that + the cache size will be increased soon, so it should be fine.

**Comment by acrrd** [comment]
Seems that we loose a bit when no code is generated but we gain from the clean up. Also considering that at some point the cache will be extend to 10Gb I don't think it will be a problem.

```
| job       | rust-cache |  now |
|-----------+------------+------|
| registry  |          0 |  129 |
| format    |        129 |    0 |
| check     |        415 |  305 |
| clippy    |        415 |  305 |
| test      |        489 |  663 |
| tarpaulin |        508 |  591 |
| build     |        412 |  663 |
|-----------+------------+------|
| Total     |       2368 | 2656 |
```

**Comment by acrrd** [comment]
https://github.com/xaynetwork/xayn_ai/actions/runs/1526294575 release ci run
bors try

**Comment by acrrd** [comment]
bors try

**Comment by acrrd** [comment]
bors try

**Comment by acrrd** [comment]
bors try-

**Comment by acrrd** [comment]
bors try

**Review by janpetschexain — APPROVED** [review]

**Comment by acrrd** [comment]
bors merge

**Comment by acrrd** [comment]
bors cancel

**Comment by acrrd** [comment]
bors merge

**Comment by acrrd** [comment]
bors cancel

**Comment by acrrd** [comment]
bors merge

**Comment by acrrd** [comment]
bors cancel

**Comment by acrrd** [comment]
bors merge

**Pull request closed without merging**
