### PR TITLE
[Merged by Bors] - FIX: data scripts

### PR DESCRIPTION
**Pull request by janpetschexain**
**Summary**

- data upload script: filter macos index file from fingerprint file
- data download script: remove asset linking (not needed anymore since #307) and remove asset flag argument

### CODE REVIEW

**Review by Robert-Steiner — APPROVED** [review]

**Comment by janpetschexain** [comment]
bors merge

**Comment by janpetschexain** [comment]
bors merge

**Comment by janpetschexain** [comment]
bors cancel

**Comment by jorge-cr-13** [comment]
bors ping

**Comment by jorge-cr-13** [comment]
bors try

**Comment by jorge-cr-13** [comment]
bors cancel

**Comment by janpetschexain** [comment]
bors merge

**Pull request closed without merging**
