### PR TITLE
Ported changes to query_count bound checks to release.

### PR DESCRIPTION
**Pull request by rustonaut**
WARNING: Meant to merge to `release`.

### CODE REVIEW

**Comment by rustonaut** [comment]
Added updates to CHANGELOG and dart package version.

**Review by acrrd — APPROVED** [review]

**Comment by acrrd** [comment]
We need to backport this to master

**Comment by rustonaut** [comment]
I hadn't much to do with release handling. 

Do we still need to tag it?

**Comment by rustonaut** [comment]
> We need to backport this to master

Besides the CHANGELOG/version changes the code is in the https://github.com/xaynetwork/xayn_ai/pull/182 PR.

But I guess it's simpler to have  a separate "cherry-picked" PR.

**Comment by acrrd** [comment]
> Do we still need to tag it?

Yes, I'll do it later today.

**Pull request merged**
